#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "kali-linux-2.0-amd64" {
    set isofile="/theCoder/iso/kali-linux-2.0-amd64.iso"
    echo "setting loopback..."
    loopback loop (hd0,3)$isofile
    echo "loading linux kernel..."
    linux (loop)/live/vmlinuz boot=live findiso=$isofile noconfig=sudo username=root hostname=kali
    echo "loading initial ramdisk..."
    initrd (loop)/live/initrd.img
}

menuentry "ubuntu-17.04-amd64.iso" {
    set isofile="/kripa432/iso/ubuntu-17.04-desktop-amd64.iso"
    echo "setting loopback..."
    loopback loop (hd0,7)$isofile
    echo "loading linux kernel..."
    linux (loop)/casper/vmlinuz.efi boot=casper iso-scan/filename=$isofile noprompt noeject quiet splash toram
    echo "loading initial ramdisk..."
    initrd (loop)/casper/initrd.lz
}
